Repository prgrms-be-devcourse/NBE4-5-1-Team09, pull requests merged in 2025-02, with the labels that each got.

#28 Feat/#24 user domain refactor
  README.md
  backend/build.gradle
  backend/src/main/java/com/example/cafe/domain/item/controller/ItemController.java
  backend/src/main/java/com/example/cafe/domain/item/dto/ItemRequestDto.java
  backend/src/main/java/com/example/cafe/domain/item/dto/ItemResponseDto.java
  backend/src/main/java/com/example/cafe/domain/item/service/ItemService.java
  backend/src/main/java/com/example/cafe/domain/member/controller/MemberController.java
  backend/src/main/java/com/example/cafe/domain/member/dto/AdminJoinRequestDto.java
  backend/src/main/java/com/example/cafe/domain/member/dto/EmailVerificationRequestDto.java
  backend/src/main/java/com/example/cafe/domain/member/dto/LoginRequestDto.java
  backend/src/main/java/com/example/cafe/domain/member/dto/MemberJoinRequestDto.java
  backend/src/main/java/com/example/cafe/domain/member/service/AuthTokenService.java
  backend/src/main/java/com/example/cafe/domain/member/service/EmailVerificationService.java
  backend/src/main/java/com/example/cafe/domain/member/service/MailService.java
  backend/src/main/java/com/example/cafe/domain/member/service/MemberService.java
  backend/src/main/java/com/example/cafe/global/config/AppConfig.java
  backend/src/main/java/com/example/cafe/global/constant/ErrorMessages.java
  backend/src/main/java/com/example/cafe/global/dto/RsData.java
  backend/src/main/java/com/example/cafe/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/example/cafe/global/exception/ServiceException.java
  backend/src/main/resources/application-test.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/com/example/cafe/domain/member/controller/MemberControllerTest.java
  backend/src/test/java/com/example/cafe/domain/member/service/MemberServiceTest.java
Labels: Refactor

#32 Feat/#5 trade shopping cart
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/example/cafe/domain/item/entity/Item.java
  backend/src/main/java/com/example/cafe/domain/trade/domain/dto/request/ItemCartRequestDto.java
  backend/src/main/java/com/example/cafe/domain/trade/domain/dto/request/OrderRequestItemDto.java
  backend/src/main/java/com/example/cafe/domain/trade/domain/dto/request/OrderRequestItemsDto.java
  backend/src/main/java/com/example/cafe/domain/trade/domain/dto/response/ItemCartResponseDto.java
  backend/src/main/java/com/example/cafe/domain/trade/domain/dto/response/OrderResponseDto.java
  backend/src/main/java/com/example/cafe/domain/trade/domain/entity/TradeStatus.java
  backend/src/main/java/com/example/cafe/domain/trade/portone/controller/PortoneController.java
  backend/src/main/java/com/example/cafe/domain/trade/portone/domain/dto/RefundMessageResponse.java
  backend/src/main/java/com/example/cafe/domain/trade/portone/domain/dto/WebHook.java
  backend/src/main/java/com/example/cafe/domain/trade/portone/service/PortoneService.java
  backend/src/main/java/com/example/cafe/domain/trade/repository/CartRepository.java
  backend/src/main/java/com/example/cafe/domain/trade/repository/TradeRepository.java
  backend/src/main/java/com/example/cafe/domain/trade/service/user/UserCartService.java
  backend/src/main/java/com/example/cafe/domain/trade/service/user/UserTradeService.java
  backend/src/main/resources/application-SECRET-KEY.yml
  backend/src/main/resources/application.yml
Labels: Feat

#34 Feat/#27 trade order
  backend/src/main/java/com/example/cafe/domain/trade/domain/entity/TradeStatus.java
  backend/src/main/java/com/example/cafe/domain/trade/repository/CartRepository.java
  backend/src/main/java/com/example/cafe/domain/trade/service/user/UserCartService.java
  backend/src/main/java/com/example/cafe/domain/trade/service/user/UserTradeService.java
Labels: Feat, Bug

#36 feat: 유저 도메인 로그아웃, 탈퇴 기능 추가
  backend/src/main/java/com/example/cafe/domain/member/controller/MemberController.java
  backend/src/main/java/com/example/cafe/domain/member/dto/ChangePasswordRequestDto.java
  backend/src/main/java/com/example/cafe/domain/member/service/MemberService.java
Labels: Feat

#38 feat: 장바구니 카트에서 주문하기, 상품 상세페이지에서 상품 단건으로 주문하기 기능 구현
  backend/src/main/java/com/example/cafe/domain/trade/controller/user/UserTradeController.java
  backend/src/main/java/com/example/cafe/domain/trade/domain/dto/request/OrderRequestItemDto.java
  backend/src/main/java/com/example/cafe/domain/trade/domain/dto/request/OrderRequestItemsDto.java
  backend/src/main/java/com/example/cafe/domain/trade/portone/controller/PortoneController.java
  backend/src/main/java/com/example/cafe/domain/trade/service/user/UserTradeService.java
  backend/src/main/resources/application.yml
Labels: Feat

#41 feat: swagger 추가
  backend/src/main/java/com/example/cafe/CafeApplication.java
  backend/src/main/java/com/example/cafe/domain/member/controller/MemberController.java
  backend/src/main/resources/application.yml
Labels: Feat

#44 test: 테스트 코드 추가
  backend/src/main/java/com/example/cafe/domain/member/controller/MemberController.java
  backend/src/main/java/com/example/cafe/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/example/cafe/global/handler/GlobalExceptionHandler.java
  backend/src/test/java/com/example/cafe/domain/member/controller/MemberControllerTest.java
  backend/src/test/java/com/example/cafe/domain/member/service/MemberServiceTest.java
  backend/src/test/java/com/example/cafe/integration/MemberIntegrationTest.java
Labels: Feat

#47 Feat/#27 trade order
  backend/src/main/java/com/example/cafe/domain/trade/controller/user/UserCartController.java
  backend/src/main/java/com/example/cafe/domain/trade/controller/user/UserTradeController.java
  backend/src/main/java/com/example/cafe/domain/trade/domain/dto/response/CartListResponseDto.java
  backend/src/main/java/com/example/cafe/domain/trade/domain/entity/Cart.java
  backend/src/main/java/com/example/cafe/domain/trade/service/user/UserCartService.java
  backend/src/main/java/com/example/cafe/domain/trade/service/user/UserTradeService.java
  backend/src/main/resources/application-secret.yml
  backend/src/main/resources/application.yml
Labels: Feat

#49 Feat/#27 trade order
  backend/src/main/java/com/example/cafe/domain/item/entity/Item.java
  backend/src/main/java/com/example/cafe/domain/trade/portone/service/PortoneService.java
  backend/src/main/java/com/example/cafe/domain/trade/service/user/UserCartService.java
  backend/src/main/java/com/example/cafe/domain/trade/service/user/UserTradeService.java
  backend/src/main/resources/application.yml
Labels: Feat, Bug

#50 Feat/#27 trade order
  backend/src/main/java/com/example/cafe/CafeApplication.java
  backend/src/main/java/com/example/cafe/domain/trade/controller/admin/AdminTradeController.java
  backend/src/main/java/com/example/cafe/domain/trade/controller/user/UserCartController.java
  backend/src/main/java/com/example/cafe/domain/trade/controller/user/UserTradeController.java
  backend/src/main/java/com/example/cafe/domain/trade/domain/dto/request/AdminConfirmRequestDto.java
  backend/src/main/java/com/example/cafe/domain/trade/domain/dto/request/CancelRequestDto.java
  backend/src/main/java/com/example/cafe/domain/trade/domain/entity/TradeStatus.java
  backend/src/main/java/com/example/cafe/domain/trade/portone/controller/PortoneController.java
  backend/src/main/java/com/example/cafe/domain/trade/portone/service/PortoneService.java
  backend/src/main/java/com/example/cafe/domain/trade/service/admin/AdminTradeService.java
  backend/src/main/java/com/example/cafe/domain/trade/service/user/UserCartService.java
  backend/src/main/java/com/example/cafe/domain/trade/service/user/UserTradeService.java
Labels: Feat

#52 Feat/#27 trade order
  backend/build.gradle
  backend/src/main/java/com/example/cafe/domain/item/repository/ItemRepository.java
  backend/src/main/java/com/example/cafe/domain/trade/service/user/UserTradeService.java
  backend/src/main/resources/application-test.yml
  backend/src/test/java/com/example/cafe/domain/trade/service/user/UserTradeServiceTest.java
Labels: Feat, Bug

#54 Feat/#53 관리자 권한 확인용 어노테이션 추가
  backend/src/main/java/com/example/cafe/domain/item/controller/ItemController.java
  backend/src/main/java/com/example/cafe/domain/member/controller/MemberController.java
  backend/src/main/java/com/example/cafe/domain/member/dto/MemberProfileDto.java
  backend/src/main/java/com/example/cafe/domain/member/service/MemberService.java
  backend/src/main/java/com/example/cafe/domain/review/controller/ReviewController.java
  backend/src/main/java/com/example/cafe/domain/trade/controller/admin/AdminTradeController.java
  backend/src/main/java/com/example/cafe/global/annotation/CheckPermission.java
  backend/src/main/java/com/example/cafe/global/aop/CheckPermissionAspect.java
  backend/src/main/java/com/example/cafe/global/config/SecurityConfig.java
  backend/src/main/java/com/example/cafe/global/handler/CustomAccessDeniedHandler.java
  backend/src/main/java/com/example/cafe/global/handler/GlobalExceptionHandler.java
  backend/src/main/java/com/example/cafe/global/util/JwtAuthenticationFilter.java
  backend/src/test/java/com/example/cafe/integration/MemberIntegrationTest.java
Labels: Feat

#56 Bug/#55 테스트 엔드포인트 수정
  backend/src/test/java/com/example/cafe/domain/member/controller/MemberControllerTest.java
Labels: Bug

#57 Feat/#27 trade order
  backend/build.gradle
  backend/src/main/java/com/example/cafe/domain/item/repository/ItemRepository.java
  backend/src/main/java/com/example/cafe/domain/trade/controller/user/UserTradeController.java
  backend/src/main/java/com/example/cafe/domain/trade/domain/dto/response/CancelResponseDto.java
  backend/src/main/java/com/example/cafe/domain/trade/portone/service/PortoneService.java
  backend/src/main/java/com/example/cafe/domain/trade/service/user/UserTradeAtomicUpdateService.java
  backend/src/main/java/com/example/cafe/domain/trade/service/user/UserTradeRedisLockService.java
  backend/src/main/java/com/example/cafe/domain/trade/service/user/UserTradeService.java
  backend/src/main/java/com/example/cafe/global/config/RedissonConfig.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/example/cafe/domain/trade/service/user/UserTradeServiceLoadTest.java
Labels: Feat

#58 Feat/#27 trade order
  backend/src/main/java/com/example/cafe/domain/trade/domain/dto/request/AdminConfirmRequestDto.java
  backend/src/main/java/com/example/cafe/domain/trade/service/admin/AdminTradeService.java
Labels: Feat, Bug

#59 Feat/#45 db migration
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/example/cafe/global/util/JwtAuthenticationFilter.java
  backend/src/main/resources/application.yml
Labels: Feat

#62 Feat/#27 trade order
  backend/.gitignore
  backend/src/main/java/com/example/cafe/domain/item/entity/Item.java
  backend/src/main/java/com/example/cafe/domain/member/service/AuthTokenService.java
  backend/src/main/java/com/example/cafe/domain/trade/controller/user/UserCartController.java
  backend/src/main/java/com/example/cafe/domain/trade/controller/user/UserTradeController.java
  backend/src/main/java/com/example/cafe/domain/trade/domain/dto/request/ItemCartRequestDto.java
  backend/src/main/java/com/example/cafe/domain/trade/domain/dto/request/OrderRequestItemDto.java
  backend/src/main/java/com/example/cafe/domain/trade/domain/dto/response/OrdersResponseDto.java
  backend/src/main/java/com/example/cafe/domain/trade/domain/entity/TradeStatus.java
  backend/src/main/java/com/example/cafe/domain/trade/service/user/UserCartService.java
  backend/src/main/java/com/example/cafe/domain/trade/service/user/UserTradeAtomicUpdateService.java
  backend/src/main/java/com/example/cafe/domain/trade/service/user/UserTradeRedisLockService.java
  backend/src/main/resources/application-secret.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/com/example/cafe/domain/trade/service/user/UserTradeServiceTest.java
Labels: Feat

#68 Feat/#60 frontend user
  frontend/next.config.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/_app.js
  frontend/src/app/account/page.tsx
  frontend/src/app/account/profile/page.tsx
  frontend/src/app/admin-login/page.tsx
  frontend/src/app/admin-signup/page.tsx
  frontend/src/app/admin/page.tsx
  frontend/src/app/change-password/page.tsx
  frontend/src/app/delete-member/page.tsx
  frontend/src/app/forgot-password/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/login/page.tsx
  frontend/src/app/page.tsx
  frontend/src/app/products/[id]/page.tsx
  frontend/src/app/products/category/[category]/page.tsx
  frontend/src/app/products/page.tsx
  frontend/src/app/products/search/page.tsx
  frontend/src/app/products/status/[status]/page.tsx
  frontend/src/app/products/top-rated/page.tsx
  frontend/src/app/profile-update/page.tsx
  frontend/src/app/profile/page.tsx
  frontend/src/app/reset-password/page.tsx
  frontend/src/app/signup/admin/page.tsx
  frontend/src/app/signup/page.tsx
  frontend/src/app/styles/globals.css
  frontend/src/app/verify-email/page.tsx
  frontend/src/components/Header.tsx
  frontend/src/context/AuthContext.tsx
  frontend/tailwind.config.ts
  frontend/tsconfig.json
Labels: Feat

#69 Feat/#27 trade order
  backend/src/main/java/com/example/cafe/domain/member/entity/Member.java
  backend/src/main/java/com/example/cafe/domain/trade/controller/user/UserTradeController.java
  backend/src/main/java/com/example/cafe/domain/trade/domain/dto/response/CancelResponseDto.java
  backend/src/main/java/com/example/cafe/domain/trade/domain/dto/response/OrdersResponseDto.java
  backend/src/main/java/com/example/cafe/domain/trade/domain/entity/Cart.java
  backend/src/main/java/com/example/cafe/domain/trade/domain/entity/Trade.java
  backend/src/main/java/com/example/cafe/domain/trade/portone/service/PortoneService.java
  backend/src/main/java/com/example/cafe/domain/trade/service/user/UserTradeAtomicUpdateService.java
  backend/src/test/java/com/example/cafe/domain/trade/service/user/UserTradeServiceLoadTest.java
Labels: Feat, Bug

#74 Feat/#60 아이템 구현, 기타 오류 수정
  frontend/src/app/account/page.tsx
  frontend/src/app/account/profile/page.tsx
  frontend/src/app/admin/page.tsx
  frontend/src/app/cart/page.tsx
  frontend/src/app/change-password/page.tsx
  frontend/src/app/delete-member/page.tsx
  frontend/src/app/forgot-password/page.tsx
  frontend/src/app/login/page.tsx
  frontend/src/app/orders/page.tsx
  frontend/src/app/page.tsx
  frontend/src/app/products/page.tsx
  frontend/src/app/styles/globals.css
  frontend/src/components/Header.tsx
  frontend/src/lib/axios.ts
Labels: Feat

#76 Bug/#75 frontend fix
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/cart/page.tsx
  frontend/src/app/orders/process/page.tsx
  frontend/src/app/payment/page.tsx
  frontend/src/app/payment/select/page.tsx
  frontend/src/app/products/[id]/page.tsx
  frontend/src/components/Header.tsx
Labels: Bug

#81 feat: portone 결제 화면 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/cart/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/payment/constants.ts
  frontend/src/app/payment/page.tsx
  frontend/src/app/payment/result/page.tsx
  frontend/src/app/payment/utils.ts
Labels: Feat

#82 Feat/#45 db migration
  backend/src/main/java/com/example/cafe/domain/trade/domain/entity/Cart.java
  backend/src/main/java/com/example/cafe/global/config/SecurityConfig.java
  backend/src/main/resources/application.yml
Labels: Feat

#85 feat: 관리자 주문 전체 목록 조회
  backend/src/main/java/com/example/cafe/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/example/cafe/domain/trade/controller/admin/AdminTradeController.java
  backend/src/main/java/com/example/cafe/domain/trade/service/admin/AdminTradeService.java
  backend/src/main/resources/application-secret.yml
Labels: Feat

#87 Feat/#78 feat trade pay
  backend/src/main/java/com/example/cafe/CafeApplication.java
  backend/src/main/java/com/example/cafe/domain/trade/repository/TradeRepository.java
  backend/src/main/java/com/example/cafe/domain/trade/service/scheduler/DeliveryScheduler.java
Labels: Feat, Bug

#88 feat: 주문 취소 구현
  frontend/src/app/orders/page.tsx
  frontend/src/app/products/[id]/page.tsx
  frontend/src/app/products/page.tsx
Labels: Feat

#90 fix: 주문 취소 (수정) 기능 fix
  backend/src/main/java/com/example/cafe/domain/trade/controller/user/UserTradeController.java
  frontend/src/app/orders/page.tsx
Labels: Bug

#91 fix: 관리자 주문 현황 수정 - 배송완료, 주문 취소 목록 출력
  backend/src/main/java/com/example/cafe/domain/trade/service/user/UserTradeAtomicUpdateService.java
  frontend/src/app/orders/page.tsx
Labels: Bug

#93 fix: 결제 완료 상태에서 취소하기 버튼 재활성화
  frontend/src/app/orders/page.tsx
Labels: Bug

#99 feat: spring doc 추가
  backend/cafeDoc.json
  backend/src/main/java/com/example/cafe/global/springDoc/DevInitData.java
  backend/src/main/java/com/example/cafe/global/springDoc/SpringDocConfig.java
  backend/src/main/resources/static/images/0652617b-95a7-4f5a-adb9-a8d4515ef3a2_testcoffeeimage.jpg
Labels: Feat, Bug, Refactor
